application: smitfuel
version: 4
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /updatestats
  script: fuel.py
  login: admin

- url: /.*
  script: fuel.py

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
